apiVersion: v1
kind: PersistentVolume
metadata:
  name: res-pv
  labels:
    type: local
spec:
  storageClassName: linode-block-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr"
    